[project]
name = "python-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=23.11.0",
    "dotenv>=0.9.9",
    "pre-commit>=4.2.0",
    "pydantic>=2.11.5",
    "pylint>=3.0.2",
    "pyyaml>=6.0.2",
]
