name: Code Quality Check

on:
  push:
    branches:
      - main  # 你可以根据需要修改为其他分支

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint

      - name: Run black code style check
        run: black --check .

      - name: Run pylint code analysis
        run: pylint --rcfile=.pylintrc .